### PR TITLE
Add french system language support for Explore shortcut

### PR DESCRIPTION
**Pull request by goebish**
Probably not the best way to do it (not a Java/Kotlin expert) but this allow to use the Explore shortcut while keeping the system in french language.

### CODE REVIEW

**Comment by lvonasek** [comment]
Thanks for contribution. It will take some time until the next update is released but I am happy to include it.

**Comment by goebish** [comment]
Thank you, I'm honored to be the first contributor.
Do you think it would be possible to get the string for the current system language via a resource id or something instead of having to compare with strings for every possible languages?

**Comment by lvonasek** [comment]
Yes, that would be easy. You can add in res/values-fr/strings.xml your french texts and that would be used if you have system language in french. You can then get the string by getString(R.string.xxx).

**Comment by goebish** [comment]
Sorry that's not what I meant, I mean getting the current string from the system, making it work with any language without having to hardcode every strings in your app.

**Comment by lvonasek** [comment]
It might be possible but it would be quite hacking. I do not want to put there too much time as this might break with any future software update.

**Pull request merged**
